apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-server

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - redis-statefulset.yaml
  - deployment.yaml
  - service.yaml
  - pdb.yaml
  - hpa.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: ai-server
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ai-server
    newName: ai-server
    newTag: latest
