apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ai-server
  namespace: ai-server
  labels:
    app.kubernetes.io/name: ai-server
    app.kubernetes.io/component: pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ai-server
