apiVersion: v1
kind: Service
metadata:
  name: ai-server
  namespace: ai-server
  labels:
    app.kubernetes.io/name: ai-server
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: ai-server
---
apiVersion: v1
kind: Service
metadata:
  name: ai-server-lb
  namespace: ai-server
  labels:
    app.kubernetes.io/name: ai-server
    app.kubernetes.io/component: load-balancer
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: ai-server
